/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Principal.*;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author juanm
 */
public class Entrenamiento_IG extends javax.swing.JPanel {
    Combinacion adivinar; 
    int Intento;
    boolean admin,infinito;
    int numerIntentos;
    

    /**
     * Creates new form Entrenamiento
     * @param b
     */
    public Entrenamiento_IG(boolean b, int num) {
        if (num == -1){
        numerIntentos = 1;
        infinito = true;
        
        }else{numerIntentos = num;infinito = false;}
        admin = b;
        initComponents();
        if (!admin){verContraseña.setEnabled(false);
        verContraseña.setToolTipText("Sólo un administrador puede ver la Contraseña");}
        Intento = 1;
        adivinar = new Combinacion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        JugarCombinación = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        verContraseña = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("ENTRENAMIENTO");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        JugarCombinación.setBackground(new java.awt.Color(102, 102, 0));
        JugarCombinación.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JugarCombinación.setForeground(new java.awt.Color(0, 0, 0));
        JugarCombinación.setText("Jugar Combinación");
        JugarCombinación.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JugarCombinación.setBorderPainted(false);
        JugarCombinación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarCombinaciónActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(102, 102, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B ", "N ", "A ", "R ", "V", "M " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(102, 102, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B ", "N ", "A", "R ", "V ", "M " }));

        jComboBox3.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(102, 102, 0));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B ", "N", "A ", "R", "V", "M" }));

        jComboBox4.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(102, 102, 0));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B ", "N", "A ", "R", "V ", "M" }));

        verContraseña.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        verContraseña.setForeground(new java.awt.Color(102, 102, 0));
        verContraseña.setText("Ver Contraseña");
        verContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JugarCombinación, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(verContraseña)
                                .addGap(38, 38, 38))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JugarCombinación, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verContraseña))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JugarCombinaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarCombinaciónActionPerformed
        if ((numerIntentos >= Intento) || (infinito)){
            String aS = (String) jComboBox1.getSelectedItem();
            String bS = (String) jComboBox2.getSelectedItem();
            String cS = (String) jComboBox3.getSelectedItem();
            String dS = (String) jComboBox4.getSelectedItem();
            char a = aS.charAt(0);
            char b = bS.charAt(0);
            char c = cS.charAt(0);
            char d = dS.charAt(0);
            char [] combi = {a,b,c,d};
            Combinacion C = new Combinacion(combi);
            String s = ("Intento nº: "+ Intento + "\n" +"Posición 1º: " + a + "\n" + "Posición 2º: " + b + "\n" + "Posición 3º: " + c + "\n" + "Posición 4º: " + d  + "\n");         
            s += (a +"" + b +""+ c +""+ d +" - "+ adivinar.devolverAciertos(C) + " acierto/s, y " + adivinar.devolverColocados(C) + " colocado/s" + "\n");
            jTextArea1.append(s);
            if (adivinar.esGanadora(C)){
                JOptionPane.showConfirmDialog(this, "Enhorabuena, combinación correcta: " + adivinar.toString(), "Entrenamiento Terminado ", JOptionPane.OK_OPTION,JOptionPane.PLAIN_MESSAGE); 
                Window w = SwingUtilities.getWindowAncestor(this);
                w.setVisible(false);
            }
        }else{
            JOptionPane.showConfirmDialog(this, "Número de Intentos Finalizados. La combinación correcta era: " + adivinar.toString(), "Entrenamiento Terminado ", JOptionPane.OK_OPTION,JOptionPane.PLAIN_MESSAGE); 
             Window w = SwingUtilities.getWindowAncestor(this);
            w.setVisible(false);
        }
           

         Intento ++;
    }//GEN-LAST:event_JugarCombinaciónActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void verContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verContraseñaActionPerformed
        if(verContraseña.isSelected()){
        String s = adivinar.toString();
        jLabel2.setText(s);
        }else{
        jLabel2.setText("");
        }
    }//GEN-LAST:event_verContraseñaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JugarCombinación;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox verContraseña;
    // End of variables declaration//GEN-END:variables
}
