/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;
import Principal.*;
import java.util.ArrayList;
import java.util.Iterator;
/**
 *
 * @author juanm
 */
public class ListaPartidas_IG extends javax.swing.JPanel {
    Usuario usuario; 
    ArrayList <Partida> LPartidas;

    public ListaPartidas_IG(Usuario u) {
        initComponents();
        usuario = u;
        jLabel1.setText(jLabel1.getText() + usuario.GetUsuario());
        anyadirPartidas();
    }
    public void anyadirPartidas(){
        LPartidas = usuario.GetPartidas();  
        for (Partida P : LPartidas ){
        jComboBox1.addItem(P.toString());}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        MostrarPartida = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("PARTIDAS DE ");

        MostrarPartida.setBackground(new java.awt.Color(102, 102, 0));
        MostrarPartida.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        MostrarPartida.setForeground(new java.awt.Color(0, 0, 0));
        MostrarPartida.setText("Mostrar Partida");
        MostrarPartida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MostrarPartida.setBorderPainted(false);
        MostrarPartida.setMaximumSize(new java.awt.Dimension(140, 40));
        MostrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(MostrarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MostrarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPartidaActionPerformed
        jTextArea1.setText("");
        Partida p = PartidaElegida();
        Usuario u = p.US2();
        boolean a = true;
        int i = 1;
        for(Ronda r : p.getRondas()){
            a = !a;
            jTextArea1.append("Ronda " + i +  ", turno de adivinar de: " + u.GetUsuario() + "\n");
            jTextArea1.append(r.toString() + "######################################" + "\n");
            if(a){i++;}
            if(a){u =p.US2();}
            else{u = p.US1();}
        }
        jTextArea1.append("El ganador de la partida fue: " + p.esGanador().GetUsuario() + "\n");
    }//GEN-LAST:event_MostrarPartidaActionPerformed
    
    private Partida PartidaElegida(){
        String s = (String) jComboBox1.getSelectedItem();
        Partida p = null;
        boolean encontrado = false;
        Iterator i = LPartidas.iterator();
        while (i.hasNext() && !encontrado){
             p = (Partida) i.next();
            if(p.toString() == s){encontrado = true;}
        }
        return p;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MostrarPartida;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
