/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Principal.*;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author juanm
 */
public class RegistarIdentificar_IG extends javax.swing.JPanel {
    AlmacenLogin almacenUsuarios;
    Usuario usuario2;
    /**
     * Creates new form IdentificarRefistrarPlayer2
     */
    public RegistarIdentificar_IG(AlmacenLogin a) {
        almacenUsuarios = a;
        initComponents();
    }
    
    public Usuario getUsuarioIdentReg(){
        return(usuario2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("REGISTRO - IDENTIFICACIÓN");

        jButton1.setBackground(new java.awt.Color(102, 102, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Registrar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Identificar");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Registrarse_IG nuevoUs2 = new Registrarse_IG();
          if(JOptionPane.showConfirmDialog(this, nuevoUs2, "Registrarse",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION){
            Usuario a = nuevoUs2.getUsuario();
            if(!almacenUsuarios.registrar(a)){
                JOptionPane.showConfirmDialog(this, "Ya existe un usuario con ese nombre, pruebe con otro ", "Fallo Registro Usuario", JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showConfirmDialog(this, "Usuario registrado correctamente, bienvenido " + a.GetUsuario(), "Confirmar Usuario Registrado", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
                usuario2 = almacenUsuarios.devolverUsuario(a); 
                Window w = SwingUtilities.getWindowAncestor(this);
                w.dispose();
        }}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Identificarse_IG nuevoUs2 = new Identificarse_IG();
         if(JOptionPane.showConfirmDialog(this, nuevoUs2, "Identificarse",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE) == JOptionPane.OK_OPTION){
        Usuario a = nuevoUs2.getUsuario();
        if(!almacenUsuarios.identificar(a)){
              JOptionPane.showConfirmDialog(this, "Usuario no identificado, pruebe a registrarse ", "Confirmar Usuario Identificado", JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);  
        }else{
            JOptionPane.showConfirmDialog(this, "Usuario identificado, bienvenido " + a.GetUsuario() + ". Pulse OK si desea continuar con este usuario", "Confirmar Usuario Identificado", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
                usuario2 = almacenUsuarios.devolverUsuario(a); 
                Window w = SwingUtilities.getWindowAncestor(this);
                w.dispose();
        }}
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
